# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MTPT' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MTPT
  pod 'LookinServer', :subspecs => ['Swift'], :configurations => ['Debug']
  pod 'SnapKit', '~> 5.0.0'

  target 'MTPTTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MTPTUITests' do
    # Pods for testing
  end

end
